//! Dialect module meant to specify how kisumu lang will be lowered to different
//! IRs before being compiled to machine code.
//!

// DO NOT EDIT THIS FILE!

#![allow(dead_code)]
#![allow(unused)]
use pliron::{
    builtin::{
        attributes::{IdentifierAttr, IntegerAttr, TypeAttr},
        op_interfaces::{
            AtLeastNOpdsInterface, AtLeastNResultsInterface, IsTerminatorInterface, NOpdsInterface,
            NRegionsInterface, NResultsInterface, OneResultInterface, OperandNOfType,
            ResultNOfType, SameOperandsAndResultType, SameOperandsType, SameResultsType,
            SingleBlockRegionInterface,
        },
        types::{IntegerType, Signedness},
    },
    common_traits::Verify,
    context::{Context, Ptr},
    derive::{pliron_attr, pliron_op},
    op::Op,
    operation::Operation,
    region::Region,
    result::Result,
    r#type::{TypeHandle, Typed},
    utils::apint::APInt,
    value::Value,
    verify_err,
};
use pliron_llvm::types::PointerType;
